<?php
$store_id = Mage::app()->getStore()->getStoreId();
$config = Mage::getModel('autocompleteplus_autosuggest/config');
$uuid = $config->getUUID();
$query = htmlentities(Mage::app()->getRequest()->getParam('q'), ENT_QUOTES);

?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php if($_imgUrl): ?>
    <?php echo $_imgHtml ?>
<?php endif; ?>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
    <?php endif; ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
<?php endif; ?>
<?php if(!$config->getSmnV2($store_id)): ?>
        <script>
            var __isp_fulltext_search_obj = {
                uuid: "<?php echo $this->escapeHtml($config->getUUID()); ?>",
                store_id: <?php echo $this->escapeHtml($store_id); ?>,
                query: "<?php echo $this->escapeHtml($query); ?>",
                formkey: "<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"
            };
        </script>
<div id="isp_search_result_page"></div>
<script src="https://magento.instantsearchplus.com/js/search_result_loading_page.js?isp_platform=magento&UUID=<?php echo $this->escapeHtml($config->getUUID()); ?>&store_id=<?php echo $this->escapeHtml($store_id); ?>"></script>
<?php else: ?>
<?php
    try {
        $cv = $config->getCustomValues($store_id);
        $cv_j = json_decode($cv);
    } catch (Exception $e) {
        $cv_j = (object) array(
            'config'=>'',
            'serp_css'=>''
        );
    }
?>
    <div id="fast-config" style="display: none"><?php echo $cv_j->config; ?></div>
    <style id="fast-serp-css"><?php echo $cv_j->serp_css; ?></style>
    <script class="fast-simon-script">
        var STORE_UUID = "<?php echo $uuid; ?>";
        var STORE_ID = Number("<?php echo $store_id; ?>");
        var FAST_SEARCH_HANDLE = "instantsearchplus/result";
    </script>
    <script>const CATEGORY_ID = "<?php echo $_category->getId(); ?>" </script>
    <div id="fast-simon-serp-app" style="display:block;color: initial;background: initial"></div>
    <script src="https://fastsimon-grid.akamaized.net/init.min.js?v=<?php echo strtotime('now'); ?>"></script>

<?php endif; ?>

